networks:
  inception-network:
    name: inception-network
    driver: bridge

services:
	nginx:
		image: inception:nginx
		container_name: nginx
		build:
			context: ./requirements/nginx
      dockerfile: Dockerfile
		env_file:
			- .env
		ports:
			-	'443:443'
		networks:
			-	inception-network
		restart: unless-stopped

	mariadb:
		image: inception:mariadb
		container_name: mariadb
		build:
			context: ./requirements/mariadb
			dockerfile: Dockerfile
		env_file:
			-	.env
		expose:
			-	3306
		networks:
			-	inception-network
		restart: unless-stopped

	wordpress:
		image: inception:wordpress
		container_name: wordpress
		build:
			context: ./requirements/wordpress
			dockerfile: Dockerfile
		env_file:
			-	.env
		expose:
			-	9000
		networks:
			-	inception-network
		restart: unless-stopped

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/wordpress
      o: bind

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: volume
      device: $HOME/data/mariadb
      o: bind
